export default {
  // 登录
  auth: '/pages/auth/index',
  // 老师首页
  questionList: '/pages/question/list/index',
  // 创建问题
  questionCreate: '/pages/question/create/index',
  // 问题详情
  questionDetail: '/pages/question/detail/index',
  // 编辑问题
  questionEdit: '/pages/question/edit/index',
  // 绑定班级
  bindClass: '/pages/question/bind-class/index',
  // 速查手册
  handBook: '/pages/question/handbook/index',
  // 我创编的问题
  myQuestions: '/pages/question/my-questions/index',
  // 布置纪录
  arrangementRecord: '/pages/question/arrangement-record/index',
  // 前概念分析--列表
  analysisList: '/pages/analysis/analysis-list/index',
  // 前概念分析--详情
  analysisDetail: '/pages/analysis/analysis-detail/index',
  // 学生首页
  previewList: '/pages/preview/list/index',
  // 预习详情
  previewDetail: '/pages/preview/detail/index',
  // 做题
  exercises: '/pages/preview/exercises/index',
  // 个人首页
  profile: '/pages/profile/index',
  // 老师我的班级
  myClass: '/pages/my-class/index',
  // 历史记录
  record: '/pages/record/index'
};